import type { Metadata } from "next";
import { Gluten, Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

export const gluten_init = Gluten({
  subsets: ['latin'],
  variable: '--font-gluten',
})
export const rubik_init = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
})

export const gluten = gluten_init.variable;
export const rubik = rubik_init.variable;

export const metadata: Metadata = {
  title: "Yosh ID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${gluten} ${rubik}`}>
        <div >

        <Navbar/>
        {children}
        
        </div>
      </body>
    </html>
  );
}
